  # ================================
  # üêò Banco de Dados PostgreSQL
  # ================================
services:
  db:
    env_file: ".env"
    image: postgres:17.6
    container_name: management_system_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Portugal
    ports:
      - ${DB_PORT}
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    restart: always
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: management_system_app
    # working_dir:
    environment:
      SPRING_PROFILES_ACTIVE: ${DB_USERNAME}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRINGDOC_API_DOCS_PATH: /docs/api
      SPRINGDOC_SWAGGER_UI_PATH: /docs/swagger-ui
      FILE_UPLOAD_DIR: ${FILE_UPLOAD_DIR}
      TZ: Europe/Portugal
    ports:
      - ${APP_PORT}
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge