  # ================================
  # üêò Banco de Dados PostgreSQL
  # ================================
services:
  db:
    image: postgres:17.6
    container_name: management_system_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Portugal
    ports:
      - ${DB_PORT}
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    restart: always
    # image: 970850578559.dkr.ecr.eu-north-1.amazonaws.com/managementsystem-ecr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: management_system_app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FILE_UPLOAD_DIR: ${FILE_UPLOAD_DIR}
      TZ: Europe/Portugal
    ports:
      - ${APP_PORT}
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge