  # ================================
  # üêò Banco de Dados PostgreSQL
  # ================================
services:
  app:
    restart: always
    image: 970850578559.dkr.ecr.eu-north-1.amazonaws.com/managementsystem-ecr:latest
    container_name: management_system_app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FILE_UPLOAD_DIR: ${FILE_UPLOAD_DIR}
      TZ: Europe/Portugal
    ports:
      - ${APP_PORT}
    networks:
      - backend

networks:
  backend:
    driver: bridge